.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH IMGS2HTML 1 "imgs2html 0.2.2" "9/Oct/2002" "imgs2html"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
imgs2html \- generate HTML files from images files
.SH "SYNOPSIS"
imgs2html [\fB--interactive\fR] [\fB--suffix\fR=SUFFIX] [\fB--thumbnail-ratio\fR=SIZE]
[\fB--reverse\fR] [\fB--homepage-url\fR=URL] [\fB--icon-dir\fR=DIR] [\fB--style\fR=URL]
[\fB--icon-\fIrole\fR\-file\fR=FILE] [\fB--nav-\fIrole\fR\-str\fR=STR] [\fB--logo\fR]
[\fB--notitle\fR] [\fB--unit-str\fR=STR] [\fB--version\fR] [\fB--help\fR]
.SH "DESCRIPTION"
imgs2htmlは複数の画像ファイルを元にHTMLファイルを作成します。
.PP
このスクリプトを実行するとカレントディレクトリにある画像ファイルを探し、
それらの一覧と各画像からなるHTMLファイル群を生成します。
.PP
生成されるHTMLファイルの文字コードはISO\-2022-JPです。
.SH "OPTIONS"
以下のオプションを指定できます。
.Ip "\fB\-i\fR, \fB--interactive\fR" 4
対話的に設定事項の指定を行ってから実行できます。
（デフォルトは対話実行しません）
.Sp
なお、対話実行時に設定した値は、 \fI.imgs2html.options\fR ファイルに保存され、
再度実行した際にはその値が使われるようになります。
.Ip "\fB\-s\fR, \fB--suffix=\s-1SUFFIX\s0\fR" 4
対象とする画像の拡張子を指定します。
（デフォルトは gif です）
.Ip "\fB\-r\fR, \fB--thumbnail-ratio=\s-1SIZE\s0\fR" 4
サムネール画像の元画像からの比率を指定します。
（デフォルトは 15% です）
.Ip "\fB--reverse\fR" 4
画像をファイル名の逆順に並べます。
.Ip "\fB\-u\fR, \fB--homepage-url=\s-1URL\s0\fR" 4
ホームの\s-1URL\s0を指定します。
（デフォルトは ../ を指します。）
.Ip "\fB--icon-dir=\s-1DIR\s0\fR" 4
ナビゲーション・アイコンのディレクトリ
（デフォルトは ../image/ です）
.Ip "\fB--style=\s-1URL\s0\fR" 4
\s-1HTML\s0ファイルで利用するスタイルシートの\s-1URL\s0を指定します。
（デフォルトではスタイルシートは使いません）
.Ip "\fB--logo\fR" 4
ロゴを表示します。
（デフォルトでは表示しません）
.Ip "\fB--notitle\fR" 4
タイトル（○枚目）を表示しません。
（デフォルトでは表示します）
.Ip "\fB--htmlonly\fR" 4
\s-1HTML\s0 出力のみ行い、サムネイルを生成しません。
（デフォルトではサムネイル生成を常に行います）
.Ip "\fB--unit-str\fR=\s-1STR\s0" 4
「〜枚目」の出力を変更します。
（デフォルトでは"枚"）
.Ip "(ナビゲーションバーの設定)" 4
ナビゲーションバーの部分のアイコンや文字列などを変更するには、以下のオ
プションが利用できます。
.Sp
\fIrole\fRの部分にはそれぞれ、
\fBfirst\fR,
\fBprev\fR,
\fBnext\fR,
\fBlast\fR,
\fBlogo\fR,
\fBindex\fR,
\fBhome\fR
のいずれかが入ります。
.Ip "\fB--icon-\fR\fIrole\fR\fB\-file=\s-1FILE\s0\fR" 8
ナビゲーションバーの各位置のアイコンのファイル名を指定します。
（ファイルが存在しない場合はアイコンは表示しません）
.Ip "\fB--nav-\fR\fIrole\fR\fB\-str=\s-1STR\s0\fR" 8
ナビゲーションバーの各位置の説明文字列を設定します。
.Sp
デフォルトの設定は以下の通り：
.Ip "\fB--icon-first-file\fR	first.gif" 12
.Ip "\fB--icon-prev-file\fR	prev.gif" 12
.Ip "\fB--icon-next-file\fR	next.gif" 12
.Ip "\fB--icon-last-file\fR	last.gif" 12
.Ip "\fB--icon-home-file\fR	home.gif" 12
.Ip "\fB--icon-index-file\fR	info.gif" 12
.Ip "\fB--icon-logo-file\fR	logo.gif" 12
.Ip "\fB--nav-first-str\fR	最初のページ" 12
.Ip "\fB--nav-prev-str\fR		前のページ" 12
.Ip "\fB--nav-next-str\fR		次のページ" 12
.Ip "\fB--nav-last-str\fR		最後のページ" 12
.Ip "\fB--nav-home-str\fR		ホームページ" 12
.Ip "\fB--nav-index-str\fR	一覧" 12
.Ip "\fB--nav-logo-str\fR		ロゴ" 12
.Ip "\fB--version\fR" 4
バージョンを表示します。
.Ip "\fB\-h\fR, \fB--help\fR" 4
このヘルプを表示します。
.SH "PREREQUISITES"
このスクリプトは、画像の処理にImageMagickを利用します。
また、日本語のコード変換にnkfを利用します。
.SH "COREQUISITES"
\fBps2imgs\fRスクリプトと一緒に使うと効果的かもしれませんね。
.SH "AUTHOR"
高久 雅生 <masao@ulis.ac.jp>, 江草 由佳 <yuka@ulis.ac.jp>

.rn }` ''
.IX Title "IMGS2HTML 1"
.IX Name "imgs2html - generate HTML files from images files"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "\fB\-i\fR, \fB--interactive\fR"

.IX Item "\fB\-s\fR, \fB--suffix=\s-1SUFFIX\s0\fR"

.IX Item "\fB\-r\fR, \fB--thumbnail-ratio=\s-1SIZE\s0\fR"

.IX Item "\fB--reverse\fR"

.IX Item "\fB\-u\fR, \fB--homepage-url=\s-1URL\s0\fR"

.IX Item "\fB--icon-dir=\s-1DIR\s0\fR"

.IX Item "\fB--style=\s-1URL\s0\fR"

.IX Item "\fB--logo\fR"

.IX Item "\fB--notitle\fR"

.IX Item "\fB--htmlonly\fR"

.IX Item "\fB--unit-str\fR=\s-1STR\s0"

.IX Item "(ナビゲーションバーの設定)"

.IX Item "\fB--icon-\fR\fIrole\fR\fB\-file=\s-1FILE\s0\fR"

.IX Item "\fB--nav-\fR\fIrole\fR\fB\-str=\s-1STR\s0\fR"

.IX Item "\fB--icon-first-file\fR	first.gif"

.IX Item "\fB--icon-prev-file\fR	prev.gif"

.IX Item "\fB--icon-next-file\fR	next.gif"

.IX Item "\fB--icon-last-file\fR	last.gif"

.IX Item "\fB--icon-home-file\fR	home.gif"

.IX Item "\fB--icon-index-file\fR	info.gif"

.IX Item "\fB--icon-logo-file\fR	logo.gif"

.IX Item "\fB--nav-first-str\fR	最初のページ"

.IX Item "\fB--nav-prev-str\fR		前のページ"

.IX Item "\fB--nav-next-str\fR		次のページ"

.IX Item "\fB--nav-last-str\fR		最後のページ"

.IX Item "\fB--nav-home-str\fR		ホームページ"

.IX Item "\fB--nav-index-str\fR	一覧"

.IX Item "\fB--nav-logo-str\fR		ロゴ"

.IX Item "\fB--version\fR"

.IX Item "\fB\-h\fR, \fB--help\fR"

.IX Header "PREREQUISITES"

.IX Header "COREQUISITES"

.IX Header "AUTHOR"

